name: Deploy frontend application samuel
on:
 push:
    branches:
      - samuel
jobs:
 docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v4
      - name: Log in to DockerHub
        uses: docker/login-action@v4
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
      - name: Prepare the docker-compose run
        run: |
          ls -l
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: samuel20222105/234-deploylab-frontend:latest
      - name: Copy file via SSH
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.HOST_SERVER }}
          username: ${{ secrets.HOST_USER_NAME }}
          key: ${{ secrets.HOST_SSH_PRIVATE_KEY }}
          port: 22
          source: "docker-compose-prod.yml"
          target: "/home/ubuntu/frontend-prod"
      - name: Run docker compose
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.HOST_SERVER }}
          username: ${{ secrets.HOST_USER_NAME }}
          key: ${{ secrets.HOST_SSH_PRIVATE_KEY }}
          port: 22
          script: |
            cd /home/ubuntu/frontend-prod
            echo ${{ secrets.DOCKER_HUB_TOKEN }} | docker login --username ${{ secrets.DOCKER_HUB_USERNAME }} --password-stdin
            docker compose -f docker-compose-prod.yml down
            docker compose docker-compose-prod.yml pull
            docker compose docker-compose-prod.yml up -d
            rm -rf /home/ubuntu/frontend-prod